# Generated by Django 5.1 on 2024-11-17 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one_shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='ali_express_ratings',
        ),
        migrations.RemoveField(
            model_name='products',
            name='ratings',
        ),
    ]
