# Generated by Django 5.1 on 2024-11-21 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one_shop', '0003_alter_aliexpressratings_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductOrder',
        ),
    ]
