# Generated by Django 5.2.8 on 2026-08-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_shop', '0004_products_ishero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='user',
            field=models.JSONField(),
        ),
    ]