# Generated by Django 5.1 on 2024-11-26 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_shop', '0004_delete_productorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sizes',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
