# Generated by Django 5.1 on 2024-11-26 01:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_shop', '0005_alter_products_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='release_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
