# Generated by Django 5.1 on 2024-12-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_shop', '0006_alter_products_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='countryCode',
            field=models.CharField(default='MA', max_length=30),
            preserve_default=False,
        ),
    ]
