# Generated by Django 5.1 on 2024-12-13 16:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_shop', '0007_users_countrycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='joined_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
