# Generated by Django 5.1 on 2024-12-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_shop', '0008_alter_users_joined_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='review',
            field=models.JSONField(),
        ),
    ]
