# Generated by Django 5.1 on 2024-12-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_shop', '0009_alter_ratings_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sizes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
