# Generated by Django 5.1 on 2025-10-03 18:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("one_shop", "0013_alter_orders_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="release_date",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
