# Generated by Django 5.1 on 2025-10-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("one_shop", "0014_alter_products_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="description",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="products",
            name="name",
            field=models.JSONField(),
        ),
    ]
