databases:
  - name: Enouzadb
    plan: free
    databaseName: Enouza
    user: Enouza

services:
  - type: web
    plan: free
    name: Enouza
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn back_end.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Enouzadb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4